import json
import os
from datetime import datetime
from typing import Dict, Any

class ReportGenerator:
    """
    Handles generation of standardized JSON and Markdown reports
    for the structural engineering team.
    """

    @staticmethod
    def generate_json_report(data: Dict[str, Any], output_path: str) -> None:
        """Saves the exact pipeline output as a structured JSON file."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=4)
        print(f"[REPORT] Structured JSON saved to: {output_path}")

    @staticmethod
    def generate_markdown_report(data: Dict[str, Any], output_path: str) -> None:
        """Creates a highly professional Markdown report summarizing the assessment."""
        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        element = data.get("element_type", "UNKNOWN").upper()
        max_width = data.get("max_calibrated_width", 0.0)
        severity = data.get("severity_grade", "N/A")
        consensus = data.get("consensus", {})

        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        md_content = f"""# STRUCTURAL INTEGRITY ASSESSMENT REPORT
**Generated:** {timestamp}
**Target Element:** {element}
**Project Group:** Squad-A (UPV Project)

---

## 1. Executive Summary
An automated structural visual analysis was executed on the target **{element}** using advanced context-calibrated telemetry.

* **Assigned Severity Grade:** `{severity}`
* **Final Action Determined:** **`{consensus.get("recommended_action", "N/A").upper()}`**
* **Maximum Calibrated Crack Width:** `{max_width:.2f} mm`
* **Consensus Agreement Strength:** `{consensus.get("roles_agreed", 0)}/3` roles in alignment

---

## 2. Technical Diagnostic Data

### Sensor & Calibration Parameters
| Attribute | Assessment / Value |
| :--- | :--- |
| **Max Calibrated Width** | {max_width:.2f} mm |
| **Primary Defect Classification** | {consensus.get("primary_defect", "NONE").upper()} |
| **Engine Core Flag Score** | {consensus.get("flag_score", 0)} |

### Multi-Agent Consensus Breakdown
The consensus module evaluated structural reports from 3 distinct roles to resolve an optimal safety plan:

> **Resolved Primary Defect:** {consensus.get("primary_defect", "NONE").upper()}
> **Recommended Immediate Action:** {consensus.get("recommended_action", "N/A").upper()}

---

## 3. Engineering Recommendations
Based on a maximum calibrated measurement of **{max_width:.2f} mm**, the following protocols are triggered:
"""

        # Inject context-specific engineering recommendations
        if "ESCALATE" in consensus.get("recommended_action", "").upper():
            md_content += (
                "* **IMMEDIATE ACTION REQUIRED:** Schedule physical inspection by a Senior Structural Engineer.\n"
                "* **RESTRICTION:** Enforce structural load monitoring on this section until sign-off.\n"
                "* **DATA LOGGING:** Export raw flight imagery and sensor coordinates to central maintenance database.\n"
            )
        elif "RETEST" in consensus.get("recommended_action", "").upper():
            md_content += (
                "* **MONITOR & SCHEDULE:** Schedule a secondary close-up drone scan within 7 business days.\n"
                "* **CALIBRATION CHECK:** Verify camera optical sensor tolerances on the UAV before flight.\n"
            )
        else:
            md_content += (
                "* **ROUTINE MAINTENANCE:** Log results into the standard digital structural twin database.\n"
                "* **MONITORING:** No immediate risk detected; re-examine during standard quarterly cycles.\n"
            )

        md_content += "\n---\n*Report generated by UPV-Squad-A automated pipeline context validation systems.*"

        with open(output_path, "w", encoding="utf-8") as f:
            f.write(md_content)
        print(f"[REPORT] Human-readable Markdown report saved to: {output_path}")
